name: Build Release

on:
  workflow_dispatch:

jobs:
  build-extension:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Bump patch version
        id: bump-version
        run: |
          VERSION=$(npm version patch --no-git-tag-version)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build extension packages
        run: npm run package

      - name: Commit version bump and build assets
        run: |
          git add package.json package-lock.json packages/
          git commit -m "ci: release ${{ steps.bump-version.outputs.version }}"
          git push

      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{ steps.bump-version.outputs.version }}
          generate_release_notes: true
          make_latest: true
          files: |
            packages/*.zip